export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
